### ISSUE TITLE
v0.1.0 ROADMAP

### ISSUE THREAD

**Issue by strdr4605** [strdr4605/jump2header#3]
Here is the list of things that should be done before publishing this package.

- [x] Check if input file is `.md`
- [x] Handle more cases for header anchors https://github.com/Flet/github-slugger
- [x] Add more unit tests (Maybe test e2e tests)
- [x] Update README 
  - [ ] Table of contents
  - [x] Installation
  - [x] Usage
  - [x] API
  - [x] ...
